// plugins/owner/createthumb.js

import { config } from '../../settings.js'

export default {
  command: 'ct',
  alias: ['createthumbnail'],
  category:'owner',
  description: `Buat thumbnail preview kustom dari URL atau reply gambar, bisa tambah favicon opsional.

Format:
ct <url>
ct <url>, <url favicon>
reply gambar lalu: ct
reply gambar lalu: ct ,<url favicon>

Koma pemisah antara thumbnail utama dan favicon.`,
  help: '(reply/url)',
  typing: true,
  wait: true,

  async execute(m, context) {
    const { sock, args } = context

    const raw = args.join(' ')
    const [rawMain, rawFavicon] = raw.split(',').map(s => s?.trim())

    const hasQuotedImage = m.quoted?.type === 'imageMessage'
    const useQuotedAsMain = !rawMain && hasQuotedImage

    if (!rawMain && !useQuotedAsMain) {
      return m.reply('Kirim URL gambar atau reply gambar!\n\nContoh:\n• ct <url>\n• ct <url>, <url favicon>\n• reply gambar lalu ketik: ct\n• reply gambar lalu ketik: ct ,<url favicon>')
    }

    const mainImage = useQuotedAsMain
      ? await m.quoted.download()
      : rawMain

    const meta = await sock.uploadThumbnail(mainImage)

    if (rawFavicon) {
      const faviconMeta = await sock.uploadThumbnail(rawFavicon, { favicon: true })
      meta.faviconMmsMetadata = {
        thumbnailDirectPath: faviconMeta.thumbnailDirectPath,
        thumbnailSha256: faviconMeta.thumbnailSha256,
        thumbnailEncSha256: faviconMeta.thumbnailEncSha256,
        mediaKey: faviconMeta.mediaKey,
        mediaKeyTimestamp: faviconMeta.mediaKeyTimestamp,
        thumbnailWidth: faviconMeta.thumbnailWidth,
        thumbnailHeight: faviconMeta.thumbnailHeight
      }
    }

    const targetUrl = 'https://chat.whatsapp.com'

    await m.reply(m.chat, {
      extendedTextMessage: {
        title: 'ini Title',
        description: 'ini deskripsi',
        text: `${targetUrl}\n\nGenerated by ${config.botName}. \n> dari zapo library.`,
        matchedText: targetUrl,
        previewType: 0,
        inviteLinkGroupTypeV2: 0,
        ...meta
      }
    }, { quote: m })
  }
}