// plugins/owner/createthumb.js

import { config } from '../../settings.js'

export default {
  command: 'ct',
  alias: ['createthumbnail'],
  category: 'owner',
  description: `> Membuat thumbnail preview kustom dari URL atau reply gambar.

*Keterangan Format:*
> \`<url>\` = URL gambar.
> \`<url>, <url favicon>\` = URL gambar + URL favicon.
> (reply) = reply gambar.

contoh penggunaan:
> \`.ct <url>\`
> \`.ct <url>, <url favicon>\`
> \`.ct\` (reply gambar)`,
  help: '<url> (reply)',
  typing: true,
  wait: true,

  async execute(m, { sock, args }) {

    const raw = args.join(' ')
    const [rawMain, rawFavicon] = raw.split(',').map(s => s?.trim())

    const hasQuotedImage = m.quoted?.type === 'imageMessage'
    const useQuotedAsMain = !rawMain && hasQuotedImage

    if (!rawMain && !useQuotedAsMain) {
      return m.reply('Kirim URL gambar atau reply gambar!\n\nContoh:\n• ct <url>\n• ct <url>, <url favicon>\n• reply gambar lalu ketik: ct\n• reply gambar lalu ketik: ct ,<url favicon>')
    }

    let meta
    try {
      const mainImage = useQuotedAsMain
        ? await m.quoted.download()
        : rawMain
      if (typeof mainImage === 'string' && !/^https?:\/\//i.test(mainImage)) {
        return m.reply('URL gambar harus diawali http:// atau https://.')
      }
      if (rawFavicon && !/^https?:\/\//i.test(rawFavicon)) {
        return m.reply('URL favicon harus diawali http:// atau https://.')
      }

      meta = await sock.uploadThumbnail(mainImage)

      if (rawFavicon) {
        const faviconMeta = await sock.uploadThumbnail(rawFavicon, { favicon: true })
        meta.faviconMmsMetadata = {
          thumbnailDirectPath: faviconMeta.thumbnailDirectPath,
          thumbnailSha256: faviconMeta.thumbnailSha256,
          thumbnailEncSha256: faviconMeta.thumbnailEncSha256,
          mediaKey: faviconMeta.mediaKey,
          mediaKeyTimestamp: faviconMeta.mediaKeyTimestamp,
          thumbnailWidth: faviconMeta.thumbnailWidth,
          thumbnailHeight: faviconMeta.thumbnailHeight
        }
      }
    } catch (err) {
      console.error('[CT] thumbnail error:', err?.message || err)
      return m.reply(`Gagal membuat thumbnail: ${err?.message || 'input tidak valid.'}`)
    }

    const targetUrl = 'https://chat.whatsapp.com'

    await m.reply({
      extendedTextMessage: {
        title: 'ini Title',
        description: 'ini deskripsi',
        text: `${targetUrl}\n\nGenerated by ${config.botName}. \n> dari zapo library.`,
        matchedText: targetUrl,
        previewType: 0,
        inviteLinkGroupTypeV2: 0,
        ...meta
      }
    })
  }
}
